domain: typing.shouji.sogou.com.cn
hosts: 10.154.137.172,10.154.137.17
rules:
  data:
    minute: 3
    freq: 3
    condition: ">20"
  redis:
    minute: 3
    freq: 3
    condition: ">1"
  upgrade:
    minute: 3
    freq: 3
    condition: ">10"
  checkMess:
    minute: 3
    freq: 3
    condition: ">1"
  upMess:
    minute: 3
    freq: 3
    condition: ">1"
  sendMess:
    minute: 3
    freq: 3
    condition: ">1"
  other:
    minute: 3
    freq: 3
    condition: ">10"

# push.qqpy.sogou.com.cn:
# push-android.shouji.sogou.com.cn:
#   hosts:
#       - 10.154.137.59 
#       - 10.154.137.61 
#       - 10.154.137.79 
#       - 10.154.137.132
#       - 10.154.137.147
#       - 10.154.137.153
#       - 10.154.137.165
#       - 10.154.137.217
#       - 10.154.137.99 
#   rules:
#     - data:
#       - minute: 3
#       - freq: 3
#       - condition: > 20
#     - redis:
#       - minute: 3
#       - freq: 3
#       - condition: > 1
#     - upgrade:
#       - minute: 3
#       - freq: 3
#       - condition: > 10
#     - checkMess:
#       - minute: 3
#       - freq: 3
#       - condition: > 1
#     - upMess:
#       - minute: 3
#       - freq: 3
#       - condition: > 1
#     - sendMess:
#       - minute: 3
#       - freq: 3
#       - condition: > 1
#     - other:
#       - minute: 3
#       - freq: 3
#       - condition: > 10
